### PR TITLE
rename hookimpl

### PR DESCRIPTION
**Pull request by sofroniewn**
Renames hook_impl for `0.4.4` release, and moves magicgui to test dependencies

### CODE REVIEW

**Comment by tlambert03** [comment]
also in main now, thx

**Comment by sofroniewn** [comment]
I see you went for

```python
def napari_experimental_provide_dock_widget():
    from .annotate import annotate_module

    opts = dict(auto_call=True)
    return [
        magic_factory(x, **opts) for x in annotate_module("skimage.filters").values()
    ]
```

instead of 

```python
def napari_experimental_provide_function():
    from .annotate import annotate_module

    return [
        x for x in annotate_module("skimage.filters").values()
    ]
```

Is there any reason for the former over the later? The later to me seems much more reusable - it means that someone could take these functions and generate many different types of widget from them instead of being forced to use a magicfactory.

I guess the name of the repo is `proto-skimage-widgets`, but I was hoping we could also use this repo as a starting point for some of the workflow generator stuff (when we find the time!!)

**Comment by tlambert03** [comment]
ah nope, that was an oversight.  I'll go back to provide_function.  I agree it's a good opportunity to see how far we can take that

**Comment by sofroniewn** [comment]
nice, thanks!

**Comment by sofroniewn** [comment]
will be good to see if/ when we hit limitations

**Pull request closed without merging**
